apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ok36jfgbe-python 
  janus-idp.io/tekton: ok36jfgbe-python
  backstage.io/kubernetes-id: ok36jfgbe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok36jfgbe-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml